---Total Number of customers by country
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

---Find Total Customers by gender
SELECT 
gender,
COUNT(gender) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

---FIND Total product by category
SELECT 
catogary,
COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY catogary
ORDER BY total_product DESC

---What is the Avg cost in each category
SELECT 
catogary,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY catogary
ORDER BY avg_cost DESC

---What is the total revenue generated for each category
SELECT 
p.catogary,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.catogary
ORDER BY total_revenue DESC

---What is the total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

---What is the Distribution of sold items across countries
SELECT 
c.country,
SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity_sold DESC
